# Database credentials
#database_dev:
#  host: "s-uf63bd0cc5896674-pub.mongodb.rds.aliyuncs.com"
#  port: "3717"
#  user: "Vincent"
#  pass: "QMRhLk9m8rqXWC3X9pMJ"
#  dbname: "neofura"
#  database: "neofura"

database_test:
  #在服务器上就要用这个替换localhost
  host: "magnetdb"
  port: "27017"
  user: ""
  pass: ""
  dbname: "testdb"
  database: "testdb"